export const ALPHABET = [
    {id: 1, keyCode: 'A'},
    {id: 2, keyCode: 'Z'},
    {id: 3, keyCode: 'E'},
    {id: 4, keyCode: 'R'},
    {id: 5, keyCode: 'T'},
    {id: 6, keyCode: 'Y'},
    {id: 7, keyCode: 'U'},
    {id: 8, keyCode: 'I'},
    {id: 9, keyCode: 'I'},
    {id: 10, keyCode: 'P'},
    {id: 11, keyCode: 'Q'},
    {id: 12, keyCode: 'S'},
    {id: 13, keyCode: 'D'},
    {id: 14, keyCode: 'F'},
    {id: 15, keyCode: 'G'},
    {id: 16, keyCode: 'H'},
    {id: 17, keyCode: 'J'},
    {id: 18, keyCode: 'K'},
    {id: 19, keyCode: 'L'},
    {id: 20, keyCode: 'M'},
    {id: 21, keyCode: 'W'},
    {id: 22, keyCode: 'X'},
    {id: 23, keyCode: 'C'},
    {id: 24, keyCode: 'V'},
    {id: 25, keyCode: 'B'},
    {id: 26, keyCode: 'N'}
];